tox-envfile: deactivate for now
This module does not support tox >= 4 and causes an error

    pluggy._manager.PluginValidationError: unknown hook 'tox_configure' in plugin
    <module 'tox_envfile' from ...>

=> deactivate for now.